[package]
name = "api"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "api"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
migration = { path = "../migration" }
entity = { path = "../entity" }
actix-web = "4.3.1"
serde = { version = "1.0", features = ["derive"] }
serde-aux = "4"
config = "0.13"
env_logger = "0.10"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
tracing-log = "0.1"
nanoid = "0.4"
chrono = { version = "0.4", features = ["serde"] }

[dependencies.tokio]
version = "1.12.0"
features = ["macros", "rt-multi-thread"]

[dependencies.sea-orm-migration]
version = "0.11.0"
features = ['sqlx-postgres', 'runtime-actix-rustls']

[dev-dependencies]
reqwest = "0.11.8"
